---
title: "Day 1 - Deconstructing an Argument"
#author: "JP"
#date: "January 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Day 1: Deconstructing an Argument**

We discuss what constitutes a convincing argument, the nature of causation, and how a paper can contribute to learning in the discipline. Then we learn to systematically translate the text of a paper into the core elements of a research argument; the units of analysis, the comparisons, the concepts, the measures, the assumptions, the theory, the models, the evidence and the conclusions. Finally, we consider basic critiques of whether the measures reflect the concepts, whether the model captures the theory, and whether the conclusions follow from the premises and evidence.

*Readings:* 

- King, Gary, Robert Keohane and Sidney Verba, Designing Social Inquiry (Princeton U
Press), pp. 3-28
- Adcock, Robert and David Collier (2001), "Measurement Validity: A Shared Standard for Qualitative and Quantitative Research", American Political Science Review, 95:3
- Gerring, John (2005), "Causation: A Unified Framework for the Social Sciences", Journal of Theoretical Politics, 17:2
- [optional] Hall, Peter, “Aligning Ontology and Methodology,” in James Mahoney and Dietrich Rueschemeyer, eds. Comparative Historical Analysis in the Social Sciences (Cambridge, 2003), pp. 373-404.

*Lab Exercise:* We practice quickly deconstructing the complex arguments of published papers into simple categories, causal statements and causal diagrams.

*Lab Replication Exercise:* We familiarize ourselves with a published research paper to understand the research question, research design and key features of the data. 


## Morning

1. Introduction to the Course
2. [Lecture Slides](https://jonnyphillips.github.io/Causal_Critiques_2020/Day 1/Slides_Day_1_v8.pdf)
3. [Evaluating Aguments Exercise](https://jonnyphillips.github.io/Causal_Critiques_2020/Day 1/Evaluation_Exercises.html)
4. [Consistent Conclusions Exercises](https://jonnyphillips.github.io/Causal_Critiques_2020/Logic_exercises.html)

## Afternoon - Practicing Critiques

We will practice rapidly reading, understanding and summarizing academic arguments. You should complete the [Paper Summary Template](https://jonnyphillips.github.io/Causal_Critiques_2020/Day 1/Paper_summary_template.pdf) for each of the following papers:  
a. [Titiunik 2011](https://jonnyphillips.github.io/Causal_Critiques_2020/Day 1/Papers/Titiunik 2011.pdf)  
b. [Maoz and Russett 1993](https://jonnyphillips.github.io/Causal_Critiques_2020/Day 1/Papers/Maoz and Russett 1993.pdf)  
c. [Ross 2001](https://jonnyphillips.github.io/Causal_Critiques_2020/Day 1/Papers/Ross 2001.pdf)  
d. [Cruz and Schneider 2017](https://jonnyphillips.github.io/Causal_Critiques_2020/Day 1/Papers/Cruz_Schneider_2017.pdf)     
e. [Carnegie and Marinov 2017](https://jonnyphillips.github.io/Causal_Critiques_2020/Day 1/Papers/Carnegie and Marinov 2017.pdf)    
  
  
## Afternoon - Critiquing the Data

For the next five days we will use the study by [Titiunik 2011](https://jonnyphillips.github.io/Causal_Critiques_2020/Day 1/Papers/Titiunik 2011.pdf) to help understand what is happening in the data when we make a causal argument/critique.

The research question is "Does incumbency in Brazil improve your performance at the next election?". The research methodology is a regression discontinuity comparing close winners and losers. Use the [Mayoral Election Data from 2000](https://jonnyphillips.github.io/Causal_Critiques_2020/Replication/2000 Mayoral Elections Data.csv) and [Mayoral Election Data from 2004](https://jonnyphillips.github.io/Causal_Critiques_2020/Replication/2004 Mayoral Elections Data.csv)  to prepare them for the analysis by following the questions below (but do not do the analysis itself). 

1. What is the data sample used to answer the research question? What alternative data samples might have been used?

2. Filter both datasets to exlude the data from second-round elections. How does this alter the data sample?

3. What is the unit of analysis in the dataset? What alternative units of analysis could have been used?

4. With the 2004 data, calculate the outcome variable, "performance at the next election" used in the paper. What different measures are available?

5. With the 2000 data, create a measure of how "close" were the winners and losers to the threshold (of a tied election) used in the paper. What alternative measures could have been used?

6. With the 2000 data, create a measure of 'incumbency' for the period 2000-2004 as used in the paper. What are the alternative measures available?

7. Merge the 2000 and 2004 data into a single dataset. What 'keys' do you need to use? What type of join did you perform?

8. Save your processed dataset! We will use it tomorrow.
