---
title: "Day 5 - Constructive Critiques"
#author: "JP"
#date: "January 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We consider various strategies and techniques for overcoming weaknesses in an argument. These include the use of alternative research designs, complementary qualitative data, deriving multiple tests from theory, uncovering ‘hidden’ units, robustness tests, heterogeneity tests and placebo tests. We also talk about how to frame and articulate critiques in ways which motivate rather than discourage.

## Morning

1. [Lecture Slides](https://jonnyphillips.github.io/Causal_Critiques_2020/Day 5/Slides_Day_5_2024_v1.pdf)

*Readings:* 

- Kocker, Matthew Adam and Nuno P. Monteiro (2015), What's in a Line? Natural Experiments and the Line of Demarcation in WWII Occupied France
- Nunn, Nathan (2011), The Slave Trade and the Origins of Mistrust in Africa, American Economic Review 101 (7) (December): 3221–3252
- Kosec, Katrina (2011), Politics and Preschool The Political Economy of Investment in Pre-Primary Education
- [optional] Miller, Beth et al (2017), How To Be a Peer Reviewer: A Guide for Recent and Soon-to-be PhDs, Political Science & Politics

## Afternoon - Practicing Critiques

Students present a research paper of their own, or a paper allocated by the teacher if preferred, making the most convincing causal case possible. Other students then present constructive critiques and suggest improvements. 

## Afternoon - Critiquing the Data

1. One theory for why incumbents may do better at the next election is due to access to state resouces. So we might expect the incumbency effect to be more positive (less negative) where state resources are more important, i.e. in the North/Northeast, and more negative in the Southeast. Implement a heterogeneity test to compare the results for just Minas Gerais (MG) and Piaui (PI).

2. If our theory is correct, we should *only* find an effect at the threshold (win margin=0). Use the 'RDestimate' function (in the 'rdd' library) to perform **placebo tests** with the threshold set to distance=0.1,-0.1,0.05 and -0.05. What do we learn from these tests?

3. Design an additional test that we could implement that would provide additional evidence that incumbency has a negative electoral impact.
